version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: krono_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: krono
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - krono_net

  web:
    build: .
    container_name: krono_web
    restart: always
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:secretpassword@db:5432/krono?schema=public
      - DIRECT_URL=postgresql://postgres:secretpassword@db:5432/krono?schema=public
      - SESSION_SECRET=shoooop-super-secret-key-32-chars-minimum-length-required!
      - NEXTAUTH_SECRET=engiinshop-super-secret-key-32-chars!
      - NEXTAUTH_URL=https://kronoventure.com
      - NEXT_PUBLIC_APP_URL=https://kronoventure.com
      - QPAY_CLIENT_ID=BILEGHURGELT
      - QPAY_CLIENT_SECRET=k04dMExt
      - QPAY_INVOICE_CODE=BILEGHURGELT_INVOICE
      - QPAY_BASE_URL=https://merchant.qpay.mn/v2
      - VERIFY_MN_API_KEY=vrf_9rokHcZDkzWp5gun1-YOiDrHH7-E6njn
      - POS_SYNC_API_KEY=super_secret_pos_key_2026
      - PAYLINK_USERNAME=batmagnai.ui@gmail.com
      - PAYLINK_SIGNATURE=vfl4QBd0obvVzIFD94rCr3bbj6uOD27OHeRtp6Krtwe57dwkVBQVYwaXc+N4P0eTikHPZ20/4HhGdjNMVNkC1Q==
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - krono_net

volumes:
  pgdata:

networks:
  krono_net:
